### ISSUE TITLE
Add Personal Access Token Authentication Support

### ISSUE THREAD

**Issue by efe** [python-poetry/poetry#2348]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I'm using [personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) for installing private git repositories. However, It isn't supported by poetry.

You can see the error below.

```
$ poetry add git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git

[ValueError]
Could not parse version constraint: //MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

**Comment by finswimmer** [comment]
Hello @efe ,

thanks for reporting. However, this was reported earlier in #2062 and should be fixed once #2169 is merged.

fin swimmer

**Comment by efe** [comment]
@finswimmer Sorry, I was using an old release of Poetry. But, The bug still exists. I'd like you to re-open the issue.

I've updated Poetry to the latest version which is `1.0.5`. `poetry add` command still gives an error. However, The description is different in this case.

```
$ poetry add git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git@v0.0.1

[ValueError]
Invalid git url "git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git@v0.0.1"
```

If I remove the version,
```
$ poetry add git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git

[CalledProcessError]
Command '['git', 'clone', 'https://MY_TOKEN/x-oauth-basic@github.com/efe/my-private-repository.git', '/var/folders/qf/f1j5ss4n6ll0nkvrx_pzvrnr0000gn/T/pypoetry-git-my-private-repository8wyivpr2']' returned non-zero exit status 128.
```

Also, Deploy key auth and Personal access token auth are different methods. They have different paths.

- Personal access token auth path:
`git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git`
- Deploy key auth path:
`git+https://TOKEN_NAME:TOKEN_KEY@github.com/efe/my-private-repository.git`

BTW, my token is an alphanumeric string.

**Comment by finswimmer** [comment]
Hello @efe,

the PR I've linked isn't merged until now. So it's not included in any release of poetry. I'm still searching for a source where it is described how a deployment key looks like and what characters are allowed. Do you know any source?

fin swimmer

**Comment by setu4993** [comment]
> $ poetry add git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git@v0.0.1
> 
> [ValueError]
> Invalid git url "git+https://MY_TOKEN:x-oauth-basic@github.com/efe/my-private-repository.git@v0.0.1"
> ```

Facing the same issue on 1.1.0.

**Comment by denizdogan** [comment]
So just to verify, there is still no way to use GitHub personal access tokens in Poetry dependencies? If so, that's a pretty huge blocker for us.

**Comment by setu4993** [comment]
@denizdogan : Yup, that's correct. It has been a blocker for us, too. I have had https://github.com/python-poetry/poetry-core/pull/115 that adds that support open for a few months now.

**Comment by lalmei** [comment]
Can we reopen this  ?

**Comment by neersighted** [comment]
This is possible in Poetry 1.2 using a `repositories.<x>` and `http-basic.<x>`. It has not been implemented in the way originally requested by this issue, and there's not a reason to re-open this request at this time as credentials in the lock file is discouraged and we're not looking to add new ways to achieve such a thing.

If you're having trouble getting the Poetry 1.2/authenticator method working, please create a  Discussion or reach out on Discord.

**Comment by lalmei** [comment]
The case here is using tokens to pull a git repo, which is still not possible right ?

**Comment by neersighted** [comment]
It is possible using the standard authenticator configuration, and is tracked at the global/user level instead of the repo/pyproject.toml/poetry.lock level.

**Comment by ealtamir** [comment]
@neersighted any chance we can get a section about this in the poetry documentation? I'd be great to have some guidance as of how to do this, given that several people, myself included, didn't know it was possible to do this with Poetry. Many thanks!
