### ISSUE TITLE
poetry export generates requirements.txt with platform specific dependancies

### ISSUE THREAD

**Issue by ahmed-shariff** [python-poetry/poetry#4083]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows 10 Pro
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [poetry_bug_report_4083_pyproject.toml](https://gist.github.com/ahmed-shariff/488b3459618d1fd8aee0aa1db9ae797e)

## Issue

This is related to #2403. I am using [keyboard](https://github.com/boppreh/keyboard/blob/master/setup.py) as an example here. It has a platform specific dependency (pyobjc). While this is not an issue when using poetry itself, when exporting to `requirements.txt` it adds pyobjc also as an entry. Which is an issue when using the `requirements.txt` in a non macOS pc. 

To recreate the issue:
```bash
poetry new test_keyboard
cd .\test_keyboard\
poetry add keyboard
poetry export -f requirements.txt -o requirements.txt --without-hashes
cd ..\
python -m virtualenv .\test_keyboard_2\
.\test_keyboard_2\Scripts\Activate.ps1
pip install -r .\test_keyboard\requirements.txt
```

The output of the above in windows 10 powershell:
```
PS D:\temp> poetry new test_keyboard
Created package test_keyboard in test_keyboard
PS D:\temp> cd .\test_keyboard\
PS D:\temp\test_keyboard> poetry add keyboard
Creating virtualenv test-keyboard in D:\temp\test_keyboard\.venv
Using version ^0.13.5 for keyboard

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 11 installs, 0 updates, 0 removals

  • Installing pyparsing (2.4.7)
  • Installing atomicwrites (1.4.0)
  • Installing attrs (21.2.0)
  • Installing colorama (0.4.4)
  • Installing more-itertools (8.7.0)
  • Installing packaging (20.9)
  • Installing pluggy (0.13.1)
  • Installing py (1.10.0)
  • Installing wcwidth (0.2.5)
  • Installing keyboard (0.13.5)
  • Installing pytest (5.4.3)
PS D:\temp\test_keyboard> poetry export -f requirements.txt -o requirements.txt --without-hashes
PS D:\temp\test_keyboard> cd ..\
PS D:\temp> python -m virtualenv .\test_keyboard_2\
created virtual environment CPython3.9.5.final.0-64 in 1081ms
  creator Venv(dest=D:\temp\test_keyboard_2, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Windows)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\s84183791\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv)
    added seed packages: pip==21.1.1, setuptools==56.0.0, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
PS D:\temp> .\test_keyboard_2\Scripts\Activate.ps1
(test_keyboard_2) PS D:\temp> pip install -r .\test_keyboard\requirements.txt
Ignoring pyobjc-framework-accessibility: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-accounts: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-addressbook: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-adservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-adsupport: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-applescriptkit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-applescriptobjc: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-applicationservices: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-apptrackingtransparency: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-authenticationservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-automaticassessmentconfiguration: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-automator: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-avfoundation: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0"' don't match your environment
Ignoring pyobjc-framework-avkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-businesschat: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-calendarstore: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-callkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-cfnetwork: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-classkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-cloudkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-collaboration: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-colorsync: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-contacts: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-contactsui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-coreaudio: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-coreaudiokit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-corebluetooth: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-coredata: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-corehaptics: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-corelocation: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-coremedia: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-coremediaio: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-coremidi: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-coreml: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-coremotion: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-coreservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-corespotlight: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-coretext: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-corewlan: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-cryptotokenkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-devicecheck: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-dictionaryservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-discrecording: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-discrecordingui: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-diskarbitration: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-dvdplayback: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-eventkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-exceptionhandling: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-executionpolicy: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-externalaccessory: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-fileprovider: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-fileproviderui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-findersync: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-fsevents: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-gamecenter: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-gamecontroller: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-gamekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-gameplaykit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-imagecapturecore: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-imserviceplugin: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-inputmethodkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-installerplugins: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-instantmessage: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-intents: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0"' don't match your environment
Ignoring pyobjc-framework-interfacebuilderkit: markers 'platform_release >= "9.0" and platform_release < "11.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-iosurface: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-ituneslibrary: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-kernelmanagement: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-latentsemanticmapping: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-launchservices: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-libdispatch: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-linkpresentation: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-localauthentication: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-mapkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-mediaaccessibility: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-medialibrary: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-mediaplayer: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0"' don't match your environment
Ignoring pyobjc-framework-mediatoolbox: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-message: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release < "13.0"' don't match your environment
Ignoring pyobjc-framework-metal: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-metalkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-metalperformanceshaders: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-metalperformanceshadersgraph: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-mlcompute: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-modelio: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-multipeerconnectivity: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-naturallanguage: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-netfs: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-network: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-networkextension: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-notificationcenter: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-opendirectory: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-osakit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-oslog: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-passkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-pencilkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-photos: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-photosui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-preferencepanes: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-pubsub: markers 'platform_release >= "9.0" and platform_release < "18.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-pushkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-quartz: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-quicklookthumbnailing: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-replaykit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-safariservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-scenekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-screensaver: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-screentime: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-scriptingbridge: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-searchkit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-security: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-securityfoundation: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-securityinterface: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-servernotification: markers 'platform_release >= "10.0" and platform_release < "13.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-servicemanagement: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-social: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-soundanalysis: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-speech: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-spritekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-storekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-syncservices: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-systemconfiguration: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-systemextensions: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-uniformtypeidentifiers: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-usernotifications: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-usernotificationsui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-videosubscriberaccount: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-videotoolbox: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-virtualization: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-vision: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-webkit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Collecting keyboard==0.13.5
  Using cached keyboard-0.13.5-py3-none-any.whl (58 kB)
Collecting pyobjc-core==7.2
  Downloading pyobjc-core-7.2.tar.gz (682 kB)
     |████████████████████████████████| 682 kB 930 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'D:\temp\test_keyboard_2\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\s84183791\\AppData\\Local\\Temp\\pip-install-yiz9dmje\\pyobjc-core_3227426a8575439ebffbc6cc09bb93c3\\setup.py'"'"'; __file__='"'"'C:\\Users\\s84183791\\AppData\\Local\\Temp\\pip-install-yiz9dmje\\pyobjc-core_3227426a8575439ebffbc6cc09bb93c3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\s84183791\AppData\Local\Temp\pip-pip-egg-info-dkouhjcs'
         cwd: C:\Users\s84183791\AppData\Local\Temp\pip-install-yiz9dmje\pyobjc-core_3227426a8575439ebffbc6cc09bb93c3\
    Complete output (2 lines):
    running egg_info
    error: PyObjC requires macOS to build
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/33/ca/c1fcc24b5c0731e1a55637b98e894b624a29f6bf1ade02c6931ea0a738c7/pyobjc-core-7.2.tar.gz#sha256=9e9ec482d80ea030cdb1613d05a247f31eedabe6666d884d42dd890cc5fb0e05 (from https://pypi.org/simple/pyobjc-core/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyobjc-core==7.2 (from versions: 2.2b1, 2.2b2, 2.2, 2.3, 2.4, 2.5.1, 3.0.1, 3.0.3, 3.0.4, 3.1, 3.1.1, 3.2, 3.2.1b1, 3.2.1, 4.0b1, 4.0, 4.0.1, 4.1, 4.2, 4.2.1, 4.2.2, 5.0a1, 5.0b1, 5.0, 5.1, 5.1.1, 5.1.2, 5.2, 5.3, 6.0, 6.0.1, 6.1, 6.2, 6.2.1, 6.2.2, 7.0, 7.0.1, 7.1, 7.2)
ERROR: No matching distribution found for pyobjc-core==7.2
(test_keyboard_2) PS D:\temp>
```

**Comment by finswimmer** [comment]
Hello @ahmed-shariff,

can you please test it with the current version in master? It seems to me as this is already solved. 

You can use `pipx` to install and try out the latest version:

```
$ pip install pipx
$ pipx install --suffix=@master 'poetry @ git+https://github.com/python-poetry/poetry.git'
$ poetry@master --version
Poetry (version 1.2.0a1)
```

fin swimmer

**Comment by allenhumphreys** [comment]
Using `poetry@master` I'm still getting `pywin32` in the exported `requirements.txt` while on linux/mac. It seems that `pywin32` is getting picked up from `portalocker`

```
[[package]]
name = "portalocker"
version = "1.7.1"
description = "Wraps the portalocker recipe for easy usage"
category = "main"
optional = false
python-versions = "*"

[package.dependencies]
pywin32 = {version = "!=226", markers = "platform_system == \"Windows\""}

[package.extras]
docs = ["sphinx (>=1.7.1)"]
tests = ["pytest (>=4.6.9)", "pytest-cov (>=2.8.1)", "sphinx (>=1.8.5)", "pytest-flake8 (>=1.0.5)"]
```

But the markers don't get applied to the actual dependency listing:

```
[[package]]
name = "pywin32"
version = "301"
description = "Python for Window Extensions"
category = "main"
optional = false
python-versions = "*"
```

In requirements.txt:

```
portalocker==1.7.1; platform_system != "Windows" and python_version >= "3.7" or platform_system == "Windows" and python_version >= "3.7"
pywin32==301
```

**Comment by dimbleby** [comment]
Not sure that @allenhumphreys comment was meant for this issue, anyway it doesn't seem to be related to the `keyboard` / `pyobjc` example that this opens with?

However their report does look like it might be a duplicate of #3511?  There's an MR for that - #3512 - which works for me in similar situations, would love to see that merged...

**Comment by allenhumphreys** [comment]
@dimbleby I think you’re right, I didn’t look closely enough at the details the first time and kind of over generalized the title of this issue.

**Comment by dimbleby** [comment]
Mind you maybe I misunderstand this issue

> This is related to #2403.

it's identical to #2403, isn't it?

**Comment by ahmed-shariff** [comment]
Sorry about the delay. Yes it is identical to #2403. :)
I tried the 1.2.0a1. It seems to work for me:

```powershell
(vevn) PS D:\temp> poetry@master.exe --version                                                                                                                                                                                               Poetry (version 1.2.0a1)
(vevn) PS D:\temp> poetry@master.exe new test_keyboard                                                                                                                                                                                       Created package test_keyboard in test_keyboard
(vevn) PS D:\temp> cd .\test_keyboard\                                                                                                                                                                                                       (vevn) PS D:\temp\test_keyboard> poetry@master.exe add keyboard                                                                                                                                                                              Creating virtualenv test-keyboard in D:\temp\test_keyboard\.venv
Using version ^0.13.5 for keyboard

Updating dependencies
Resolving dependencies... (1.9s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing keyboard (0.13.5)
(vevn) PS D:\temp\test_keyboard> poetry@master.exe export -f requirements.txt -o requirements.txt --without-hashes                                                                                                                           (vevn) PS D:\temp\test_keyboard> cd ..\                                                                                                                                                                                                      (vevn) PS D:\temp> python -m virtualenv test_keyboard_2                                                                                                                                                                                      created virtual environment CPython3.9.5.final.0-64 in 690ms
  creator Venv(dest=D:\temp\test_keyboard_2, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Windows)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\s84183791\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv)
    added seed packages: pip==21.1.1, setuptools==56.0.0, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
(vevn) PS D:\temp> .\test_keyboard_2\Scripts\Activate.ps1                                                                                                                                                                                    (test_keyboard_2) PS D:\temp> which.exe pip                                                                                                                                                                                                  /d/temp/test_keyboard_2/Scripts/pip
(test_keyboard_2) PS D:\temp> pip install -r .\test_keyboard\requirements.txt                                                                                                                                                                Ignoring pyobjc-core: markers 'python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0" or platform_release >= "9.0" and platform_release < "11.0" and python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release < "13.0" or platform_release >= "9.0" and platform_release < "18.0" and python_version >= "3.6" and sys_platform == "darwin" or platform_release >= "10.0" and platform_release < "13.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-accessibility: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-accounts: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-addressbook: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-adservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-adsupport: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-applescriptkit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-applescriptobjc: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-applicationservices: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-apptrackingtransparency: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-authenticationservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-automaticassessmentconfiguration: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-automator: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-avfoundation: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0"' don't match your environment
Ignoring pyobjc-framework-avkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-businesschat: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-calendarstore: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-callkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-cfnetwork: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-classkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-cloudkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-cocoa: markers 'python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0" or platform_release >= "9.0" and platform_release < "11.0" and python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release < "13.0" or platform_release >= "9.0" and platform_release < "18.0" and python_version >= "3.6" and sys_platform == "darwin" or platform_release >= "10.0" and platform_release < "13.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-collaboration: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-colorsync: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-contacts: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-contactsui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-coreaudio: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-coreaudiokit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-corebluetooth: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-coredata: markers 'python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-corehaptics: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-corelocation: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-coremedia: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-coremediaio: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-coremidi: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-coreml: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-coremotion: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-coreservices: markers 'python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-corespotlight: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-coretext: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-corewlan: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-cryptotokenkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-devicecheck: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-dictionaryservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-discrecording: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-discrecordingui: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-diskarbitration: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-dvdplayback: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-eventkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-exceptionhandling: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-executionpolicy: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-externalaccessory: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-fileprovider: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-fileproviderui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-findersync: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-fsevents: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0" or python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-gamecenter: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-gamecontroller: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-gamekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-gameplaykit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-imagecapturecore: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-imserviceplugin: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-inputmethodkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-installerplugins: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-instantmessage: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-intents: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0"' don't match your environment
Ignoring pyobjc-framework-interfacebuilderkit: markers 'platform_release >= "9.0" and platform_release < "11.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-iosurface: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-ituneslibrary: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-kernelmanagement: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-latentsemanticmapping: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-launchservices: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-libdispatch: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-linkpresentation: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-localauthentication: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-mapkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-mediaaccessibility: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-medialibrary: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-mediaplayer: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "16.0"' don't match your environment
Ignoring pyobjc-framework-mediatoolbox: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0"' don't match your environment
Ignoring pyobjc-framework-message: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release < "13.0"' don't match your environment
Ignoring pyobjc-framework-metal: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-metalkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-metalperformanceshaders: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-metalperformanceshadersgraph: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-mlcompute: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-modelio: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-multipeerconnectivity: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-naturallanguage: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-netfs: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-network: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-networkextension: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-notificationcenter: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "14.0"' don't match your environment
Ignoring pyobjc-framework-opendirectory: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-osakit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-oslog: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-passkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-pencilkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-photos: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-photosui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-preferencepanes: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-pubsub: markers 'platform_release >= "9.0" and platform_release < "18.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-pushkit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-quartz: markers 'python_version >= "3.6" and sys_platform == "darwin" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-quicklookthumbnailing: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-replaykit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-safariservices: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-scenekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-screensaver: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-screentime: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-scriptingbridge: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "9.0"' don't match your environment
Ignoring pyobjc-framework-searchkit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-security: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-securityfoundation: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-securityinterface: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-servernotification: markers 'platform_release >= "10.0" and platform_release < "13.0" and python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-servicemanagement: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "10.0"' don't match your environment
Ignoring pyobjc-framework-social: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-soundanalysis: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-speech: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-spritekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "13.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "15.0"' don't match your environment
Ignoring pyobjc-framework-storekit: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "11.0"' don't match your environment
Ignoring pyobjc-framework-syncservices: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-systemconfiguration: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc-framework-systemextensions: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "19.0"' don't match your environment
Ignoring pyobjc-framework-uniformtypeidentifiers: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-usernotifications: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0" or python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-usernotificationsui: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-videosubscriberaccount: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "18.0"' don't match your environment
Ignoring pyobjc-framework-videotoolbox: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "12.0"' don't match your environment
Ignoring pyobjc-framework-virtualization: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "20.0"' don't match your environment
Ignoring pyobjc-framework-vision: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_release >= "17.0"' don't match your environment
Ignoring pyobjc-framework-webkit: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Ignoring pyobjc: markers 'python_version >= "3.6" and sys_platform == "darwin"' don't match your environment
Collecting keyboard==0.13.5
  Using cached keyboard-0.13.5-py3-none-any.whl (58 kB)
Installing collected packages: keyboard
Successfully installed keyboard-0.13.5
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'D:\temp\test_keyboard_2\Scripts\python.exe -m pip install --upgrade pip' command.
(test_keyboard_2) PS D:\temp>
```

**Comment by finswimmer** [comment]
Thanks a lot for your reply @ahmed-shariff and your hint about duplication @dimbleby :+1: 

So I'm closing this here.
