### ISSUE TITLE
poetry seems to ignore virtualenvs.create

### ISSUE THREAD

**Issue by cicuz** [python-poetry/poetry#4187]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian GNU/Linux 10 (Docker `python:3.6`)
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist link](https://gist.github.com/cicuz/e8749ab74376373f86f6357e68d15167)

## Issue

I recently recreated my Docker images, and replaced the old `get-poetry.py` with `install-poetry.py`, and suddenly my entry command was not working anymore, failing with `ModuleNotFoundError`.

My `poetry install` invocations correctly output `Skipping virtualenv creation, as specified in config file.`, which is what I asked via `poetry config virtualenvs.create false`, but by looking around I found them being placed in the `POETRY_HOME/venv` folder, and therefore not being found by my simple `python -m` entrypoint:

    root@71978f3d0878:/code/src# ls /opt/poetry/venv/lib/python3.6/site-packages/
    Babel-2.9.1.dist-info			       blackd				factory_boy-2.12.0.dist-info	     lockfile			      pyOpenSSL-20.0.1.dist-info	 shellingham-1.4.0.dist-info
    CacheControl-0.12.6.dist-info		       blib2to3				faker				     lockfile-0.12.2.dist-info	      pyasn1				 six-1.16.0.dist-info

Am I doing something wrong, or did something break with some of the updates I skipped?

Thanks

**Comment by cicuz** [comment]
I reverted the install script to `get-poetry.py` and it works again

```
root@4e2f6d2ab52f:/code/src# ls -lhart /opt/poetry/env 
-rw-r--r-- 1 root root 35 Jun 18 10:16 /opt/poetry/env
root@4e2f6d2ab52f:/code/src# python -c "import sys, pprint; pprint.pprint(sys.path)"
['',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/root/.local/lib/python3.6/site-packages',
 '/usr/local/lib/python3.6/site-packages',
 '/dependencies']
root@4e2f6d2ab52f:/code/src# ls /usr/local/lib/python3.6/site-packages
Babel-2.9.1.dist-info			       autopep8.py			elasticsearch-6.3.1.dist-info	    jmespath			     pycodestyle-2.7.0.dist-info	six.py
Cryptodome				       babel				elasticsearch5			    jmespath-0.10.0.dist-info	     pycodestyle.py			snowballstemmer
Cython					       black				factory				    lxml			     pycparser				snowballstemmer-2.1.0.dist-info

```

**Comment by finswimmer** [comment]
Hello @cicuz,

the new installer script `install-poetry.py` (which I would only recommend for installing poetry >=1.2.0 and its prereleases) isolate the poetry installation in its own venv. The `get-poetry.py` vendors the dependencies instead and poetry will use the currently activated python executable when running.

The downside of the isolation of poetry running in its own venv is, that it is hard to find out which python is currently activated in the shell and therefore where the global place for installing packages is.

I've already start talking about this topic with @sdispater .

fin swimmer

**Comment by cicuz** [comment]
Hello fin, thanks for getting back to me!

I'm not sure I understand all the implications of the issues you're rising though; is the discussion you mentioned a public one?

**Comment by finswimmer** [comment]
> is the discussion you mentioned a public one?

At the moment this is just a private discussion on our discord server. But you can join the [public channel](https://discordapp.com/invite/awxPgve) if you like to discuss there.

**Comment by sdispater** [comment]
@cicuz Your use case should be fixed by https://github.com/python-poetry/poetry/pull/4192.

Could you try by installing Poetry from the `1.1` branch?

```bash
python install-poetry.py --git https://github.com/python-poetry/poetry.git@1.1
```

**Comment by cicuz** [comment]
It seems to be behaving the same way. This is the code I used

`COPY ./src/dependencies /dependencies
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py --output install-poetry.py && \
    python install-poetry.py --git https://github.com/python-poetry/poetry.git@1.1 && \
    poetry config virtualenvs.create false && \
    cd /dependencies && \
    poetry install
`

**Comment by max-wittig** [comment]
We encountered the same issue with the new installer script.

@dlouzan @ercanucan

**Comment by sandpipersburg** [comment]
Below scenarios demonstrate that:
1. Poetry 1.1.7 which was installed via `install-poetry`, does not recognize the changes in Python version made via: `pyenv local <version>`. When used to bootstrap Poetry project, the expected behavior is to recognize pyenv Python version
2. Poetry becomes broken when Python version that have been active at a time of Poetry installation via curl + `install-poetry.py`, is removed via pyenv. 

Out-of-the-head suggestion is that`/Users/username/Library/Application Support/pypoetry/venv/bin/python` should link to pyenv Python shims, not to a specific pyenv Python version, as it happens currently. 

**The environment:**
- macOS Big Sur, Homebrew, the system version of Python is 2.7.16
- pyenv 2.0.3 installed via Homebrew
- Python 3.8.8 installed via pyenv and activated in a Poetry project dir (monorepo root dir) via pre-existing `.python-version` file. No other versions of Python installed via pyenv
- Poetry 1.1.7 installed via curl + `install-poetry.py` from the root dir, i.e. an active version of Python at a time of installation was 3.8.8
- Poetry appended to PATH via `.zshrc`: `export PATH="$PATH:$HOME/.local/bin"`, `echo $PATH`:
`/Users/username/.pyenv/shims:/usr/local/bin:<skipped>:/Users/username/.local/bin`
- `pyproject.toml`: `python = "^3.8.8"`
- `poetry.lock`: `python-versions = "^3.8.8"`
- `poetry.toml`: `in-project = true`
- no `.venv` present in a root dir or sub-dirs

Commands in below scenarios executed from Poetry project dir.

**Scenario 1 (positive). Bootstrap local dev env for pre-existing Poetry project:**
- `pyenv versions`. The result (w and p are softlinks to workspace and project dirs):
```zsh
  system
  3.8.8 (set by /Users/username/w/p/.python-version)
```
- `python --version`. The result:
`Python 3.8.8`
- `poetry run python --version`. The result:
```zsh
Creating virtualenv project in /Users/username/workspace/project/.venv
Python 3.8.8
```

**Scenario 2 (negative). Switch Python version via pyenv:**
- delete any `.venv` present in a project dir and below
- install Python 3.7.11 via pyenv, activate it: `pyenv local 3.7.11`
- `pyenv versions`. The result:
```zsh
  system
* 3.7.11 (set by /Users/username/w/p/.python-version)
  3.8.8
```
- `python --version`. The result:
`Python 3.7.11`
- `poetry run python --version`. The result:
```zsh
Creating virtualenv project in /Users/username/workspace/project/.venv
Python 3.8.8
```

**Expected result:**
poetry prints Python version Python 3.7.11, or maybe Python version compatibility error (because the project requires a version 3.8.8 or later). Regarding error, my understanding is that execution context of `poetry run python --version` may also be not related to the particular project, thus the minimum requirement for Python version might not apply here, and no Python version compatibility error needed. 

**Scenario 3 (negative). Removal of non-active Python version via pyenv, `.venv` is present:**
- follow Scenario 2
- `pyenv uninstall 3.8.8`, followed by: `poetry run python --version`. The result:
```zsh
/Users/username/.local/bin/poetry: line 2: /Users/username/Library/Application Support/pypoetry/venv/bin/python: No such file or directory
/Users/username/.local/bin/poetry: line 2: exec: /Users/username/Library/Application Support/pypoetry/venv/bin/python: cannot execute: No such file or directory
```

**Expected result:**
Poetry is working and either prints the actual Python version, or a reasonable and meaningful error. 

**Scenario 4 (negative). Removal of non-active Python version via pyenv, `.venv` is absent:**
- follow Scenario 3
- delete any `.venv` present in a project dir and below
- `poetry run python --version`. The result: 
the same result as for Scenario 3.

**Expected result:**
See Scenario 3.

**Comment by max-wittig** [comment]
@sandpipersburg We don't use pyenv in the container, so I think that this is a different issue. Could you delete the comment and create a separate one to not pollute this one?

**Comment by sandpipersburg** [comment]
> @sandpipersburg We don't use pyenv in the container, so I think that this is a different issue. Could you delete the comment and create a separate one to not pollute this one?

Done: [Poetry stuck at pyenv Python version active during install-poetry, broken after version uninstall #4317](https://github.com/python-poetry/poetry/issues/4317)

**Comment by thiras** [comment]
I confirm the bug

**Comment by TheGreatRefrigerator** [comment]
I still encounter this problem with the latest 1.2.0a2 release, which should contain the fix?
OS of the Docker image `Debian GNU/Linux 10 \n \l`


```
FROM tiangolo/uvicorn-gunicorn:python3.8

# get DEV argument from docker-compose file
ARG DEV

# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_HOME=/opt/poetry python - --preview && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

COPY ./pyproject.toml ./poetry.lock* /app/

RUN if [ "$DEV" = "1" ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi
```

when doing poetry install, poetry says that it skips virtual env creation (as defined by the config), but still installs all packages to `$POETRY_HOME/venv/lib` and not to `/usr/local/lib/python3.8/site-packages` which is used by the system python interpreter and where it is installed when using the get-poetry.py script.

running `python` from anywhere else than in `$POETRY_HOME/venv/lib/python3.8/site-packages/`
will not let me import the installed dependencies specified in pyproject.toml.

**Comment by sdispater** [comment]
@TheGreatRefrigerator Could you test if the `master` branch fixes the issue?

**Comment by TheGreatRefrigerator** [comment]
@sdispater Yes, version 1.1.8 fixes the issue, thanks.
Will this be included in 1.2 at some point as well?

**Comment by varneyo** [comment]
@TheGreatRefrigerator @sdispater I am using the same tiangolo codebase / project / dockerfile and have wasted a fair amount of time trying to fix this / trying to understand. Can someone provide instructions or ideally @TheGreatRefrigerator an updated docker file. Apologies Ive tried everything now and I feel like I need explaining to me like im a 5 year old to get it to work. I can see virtualenvs.create is being ignored and that site packages are ending up in /usr/lib/python3.9/site-packages which is not in my PATH.

**Comment by TheGreatRefrigerator** [comment]
@varneyo just follow the linked commit above. In that repo the setup is working. Although i think poetry switched to a different location for the install script already, which is not yet reflected.

**Comment by iSplasher** [comment]
This is still an issue with `Poetry (version 1.3.2)`

**Comment by finswimmer** [comment]
@iSplasher please open a new issue with steps to reproduce. 
This ticket here is closed for a long time.
