### ISSUE TITLE
poetry install with build script fails on 1.2.0

### ISSUE THREAD

**Issue by matteosantama** [python-poetry/poetry#4979]
```sh
❯ poetry --version
Poetry (version 1.2.0a2)
```

I am trying to run `poetry install`. This configuration works on 1.1.12

```toml
# pyproject.toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Matteo Santamaria <XXX@gmail.com>"]
readme = "README.md"
build = "build.py"

[tool.poetry.dependencies]
python = "3.8"

[tool.poetry.dev-dependencies]
numpy = "^1.22.0"

[build-system]
requires = ["poetry-core", "numpy>=1.22.0,<=1.23.0"] 
build-backend = "poetry.core.masonry.api"
```

```python
# build.py
import numpy as np

def build(setup_kwargs):
    return setup_kwargs
```

but fails on 1.2.0a2.

Tested on macOS Monterey Version 12.0.1 Apple M1 Pro

**Comment by matteosantama** [comment]
It's worth mentioning that I am running these commands in a virtual environment **not** managed by `poetry`

**Comment by finswimmer** [comment]
Hello @matteosantama,

this is a duplicate of https://github.com/python-poetry/poetry/issues/2789.

fin swimmer

**Comment by matteosantama** [comment]
@finswimmer I've updated my original post the better reflect the problem. What I've identified is related to your linked issue, but different in that it demonstrates a 1.1.x -> 1.2.x regression. Any project that uses a build script this way will be adversely impacted by upgrading to 1.2.x

I think this issue should be re-opened and placed in the **1.2** milestone.

**Comment by hdk5** [comment]
I second this issue.

It should be noted that this issue does not happen with `build` command, and is caused by `--use-pep517` flag usage for `pip install`

**Comment by abn** [comment]
@matteosantama can you provide a bit more detail on the error?

**Comment by abn** [comment]
Reopening this as the issue exists when a `setup.py` file was generated forcefully. Do note that build scripts are still an experimental feature and breakages can occur.

#5590 should fix the reported issue. Additionally, #5401 should improve the experience when `generate-setup-file = false`.

**Comment by Nischala23** [comment]
I'm still having this issue with my docker build. I get the following error "Version 1.2.0 is not supported by this installer!". However I'm using the poetry 1.20 in my local env and it works just fine. Anyone knows how I can fix this. I'm using the following

**Comment by neersighted** [comment]
This issue tracks `setup.py` + build script support. The issue you are having is use of an unsupported, deprecated installer (#6377 for more details) -- you need to migrate to install.python-poetry.org as described in the [documentation](python-poetry.org/docs/#installation) or [release announcement](https://python-poetry.org/blog/announcing-poetry-1.2.0/)

**Comment by Nischala23** [comment]
Thanks for the quick response @neersighted I was able to install poetry. However, I'm running into issues with the path and unable to find poetry in my Docker file. Below is what I'm running. Apologies if I'm posting this on the wrong thread

RUN /bin/bash -ci "curl -sSL https://install.python-poetry.org | python -"
RUN echo "source $HOME/.local/bin" >> /root/.bashrc
RUN /bin/bash -ci "poetry config virtualenvs.create false"
RUN /bin/bash -ci "poetry --version"

**Comment by neersighted** [comment]
You should set environmental variables in a Dockerfile using the `ENV` directive.

```dockerfile
RUN curl -sSL https://install.python-poetry.org/ | python - --version 1.2.0
ENV PATH="$HOME/.local/bin:$PATH"
RUN poetry --version
```

Please do not turn off virtualenv creation -- you are likely to run into way more problems for no benefit. The ability to turn off virtualenv creation was intended as a "I know what I am doing" feature for very advanced users -- if you don't know why you need it off, you do not need it off -- see #6398 for a roundup issue on this topic.

Finally, please don't use this issue for support -- you are sending notifications to everyone who has participated in it for something that is irrelevant and already considered solved. Please start a Discussion on the discussion tab, or join the Discord server if you need support from the community.
