### ISSUE TITLE
Poetry creates virtualenv with wrong version 

### ISSUE THREAD

**Issue by EdatWork** [python-poetry/poetry#5190]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **macOS BigSur 11.6.1 (20G224)**: 
- **Poetry version 1.1.13**: 
- **Seems unrelated to [pyproject.toml](https://gist.github.com/EdatWork/1f525e8e8970b84dcc7e36d8448e24b7)**

## Issue

I'm trying to constrain the python version within 3.9.x using:
```
[tool.poetry.dependencies]
python = "~3.9.0"
```

I have a setup of `poetry` + `pyenv` that has been working nicely so far, but poetry insists on using `Python 3.10`.
It tells me that it's using `3.9.9` but it runs python `3.10`. Somehow it creates the virtualenv with the wrong version.
![image (2)](https://user-images.githubusercontent.com/99500802/153640594-0fd5d2b4-db39-4c2e-8a8a-61e04bc259b0.png)

Pyenv has been set with `pyenv local 3.9.9` and seems to be working correctly

![image (3)](https://user-images.githubusercontent.com/99500802/153640556-3942e745-cb3c-49aa-8246-9d7246a7ca85.png)

Things I've tried:
 - `poetry env use 3.9.9`
 - Delete everything (lock, venv, even cloning again) and trying again
 - tried to use another folder name (in case something was cached)
 - Ran with -vvv to check if I had more output about the venv creation

Thanks for the help!!

**Comment by muraii** [comment]
I don't want to create a nearly duplicate issue, but the issue I'm having is slightly different. If y'all prefer, I'll create a new issue.

### Issue:
Running ```curl -sSL https://install.python-poetry.org | python -``` installs Poetry without any errors or apparent issues. However, any attempt to use `poetry new` or `poetry init` will choose the version of Python which which Poetry was installed, independent of which version of Python has been selected as global using `pyenv global <version>`.

### System
* Windows 10 -> WSL2
* Manjaro 21.2.1
* `pyenv` version 2.2.3-1-g423de9ae
* `poetry` version 1.1.13
* `zsh` 5.8

### Steps to reproduce:
```$ pyenv global 3.9.9
$ curl -sSL https://install.python-poetry.org | python -
$ poetry new test
$ cd test
$ poetry shell
$ python -V

Python 3.9.9

$ cd ..
$ pyenv global 3.8.5
$ poetry new test2
$ cd test2
$ poetry shell
$ python -V

Python 3.9.9
```
### Short-term Fix
If I use `poetry env use 3.8.5` or whatever other version I want, and _then_ create/activate a virtual environment with `poetry shell`, Poetry uses the appropriate Python version. But I _think_ this is not expected behavior, i.e., Poetry should (and on an Ubuntu system I've used previously, Poetry _does_) choose the version of Python based on the currently activated Python version per `pyenv`.

**Comment by mabugaj** [comment]
For me it's the same situation. Problem in general is that poetry shows that it's installing right version but in `.venv` actually is being installed something else:

```bash
➜ poetry install -E redis           
The currently activated Python version 3.10.2 is not supported by the project (3.9.7).
Trying to find and use a compatible version. 
Using python3 (3.9.7)
Creating virtualenv pro-test in /home/bugaj/Documents/git/pro-test/code/.venv
Installing dependencies from lock file
```

After this in .venv python 3.10 is installed.

**Comment by arubin** [comment]
I am getting the same inconsistent behavior - my current solution is to manually edit the virtual environment config poetry generates:
1. Edit pyvenv.cfg in the Poetry virtual env folder 
  - for my config that is located ~/Library/Caches/pypoetry/virtualenvs/<virtual-env>
  - point all the python directories to my desired pyenv version
2. Update the 'python' symlink in  <virtual-env>/bin
  - for my config this is located at ~/Library/Caches/pypoetry/virtualenvs/<env-name>/bin
  - create a new symbolic link: `ln -s <pyenv executable> ./python`

**Comment by finswimmer** [comment]
I think this a duplicate of https://github.com/python-poetry/poetry/issues/5077#issuecomment-1018416532.

**Comment by mabugaj** [comment]
@finswimmer I think You're right (the process that You described is exactly the way I got into this situation), so the problem is with the new installation script. For the record I tried old installation script but it has other bugs on my system (latest manjaro).

One problem that I see is that I'm using `1.1.13` which should have this feature merged or am I wrong?

**Comment by muraii** [comment]
> I think this a duplicate of [#5077 (comment)](https://github.com/python-poetry/poetry/issues/5077#issuecomment-1018416532).

Might be, but for my part I'd read that thread and comment and used the newer installation script after uninstalling the Poetry instance I'd installed using the older script. And this happens for whichever version of Python with which I install Poetry, so it _shouldn't_ be a residual install issue.

**Comment by mijamo** [comment]
For me the problem seemed to be that by default 3.10 included a `local` folder but no `bin` (`bin` was nested into `local`). I created a symlink from `local/bin` to `bin` and it seemed to work after that

**Comment by timbedard** [comment]
Yeah, this happens for me even with the latest beta. 🫤

**Comment by finswimmer** [comment]
Hey,

this should now work correctly by setting `virtualenvs.prefer-active-python` to `true`.

fin swimmer

**Comment by SubaruSpirit** [comment]
> Hey,
> 
> this should now work correctly by setting `virtualenvs.prefer-active-python` to `true`.
> 
> fin swimmer

It didn't solve the problem though. I specified python version to be ^3.9, but it created python 3.10.4 in the virtual env
