### ISSUE TITLE
[1.2.0b2.dev0] Add package error TooManyRedirects

### ISSUE THREAD

**Issue by swicaksono** [python-poetry/poetry#5802]
Several days ago I added a new package from my private repo that was doing fine, but today I tried to add a new package getting an error
 
```bash
TooManyRedirects

 Exceeded 30 redirects.
```
I already tried to clear the cache but using the current version and new version (1.2.0b3.dev0) I still got the issue.
Here, is the capture of execution using debug mode.

**version. 1.2.0b2.dev0**
```bash
 Stack trace:

  5  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py:231 in _get
      229│     def _get(self, endpoint: str) -> dict | None:
      230│         try:
    → 231│             json_response = self.session.get(self._base_url + endpoint)
      232│         except requests.exceptions.TooManyRedirects:
      233│             # Cache control redirect loop.

  4  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:542 in get
      540│ 
      541│         kwargs.setdefault('allow_redirects', True)
    → 542│         return self.request('GET', url, **kwargs)
      543│ 
      544│     def options(self, url, **kwargs):

  3  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:529 in request
      527│         }
      528│         send_kwargs.update(settings)
    → 529│         resp = self.send(prep, **send_kwargs)
      530│ 
      531│         return resp

  2  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:667 in send
      665│             # Redirect resolving generator.
      666│             gen = self.resolve_redirects(r, request, **kwargs)
    → 667│             history = [resp for resp in gen]
      668│         else:
      669│             history = []

  1  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:667 in <listcomp>
      665│             # Redirect resolving generator.
      666│             gen = self.resolve_redirects(r, request, **kwargs)
    → 667│             history = [resp for resp in gen]
      668│         else:
      669│             history = []

  TooManyRedirects

  Exceeded 30 redirects.

  at ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│ 
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
      167│ 
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│ 

The following error occurred when trying to handle this error:


  Stack trace:

  23  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  22  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/console/application.py:174 in _run
       172│         self._load_plugins(io)
       173│ 
     → 174│         return super()._run(io)
       175│ 
       176│     def _configure_io(self, io: IO) -> None:

  21  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

  20  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cleo/application.py:467 in _run_command
       465│ 
       466│         if error is not None:
     → 467│             raise error
       468│ 
       469│         return event.exit_code

  19  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cleo/application.py:451 in _run_command
       449│ 
       450│             if event.command_should_run():
     → 451│                 exit_code = command.run(io)
       452│             else:
       453│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  18  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

  17  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

  16  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/console/commands/add.py:148 in handle
       146│             return 0
       147│ 
     → 148│         requirements = self._determine_requirements(
       149│             packages,
       150│             allow_prereleases=self.option("allow-prereleases"),

  15  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/console/commands/init.py:357 in _determine_requirements
       355│             elif "version" not in requirement:
       356│                 # determine the best version automatically
     → 357│                 name, version = self._find_best_version_for_package(
       358│                     requirement["name"],
       359│                     allow_prereleases=allow_prereleases,

  14  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/console/commands/init.py:392 in _find_best_version_for_package
       390│ 
       391│         selector = VersionSelector(self._get_pool())
     → 392│         package = selector.find_best_candidate(
       393│             name, required_version, allow_prereleases=allow_prereleases, source=source
       394│         )

  13  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/version/version_selector.py:39 in find_best_candidate
        37│             },
        38│         )
     →  39│         candidates = self._pool.find_packages(dependency)
        40│         only_prereleases = all(c.version.is_unstable() for c in candidates)
        41│ 

  12  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pool.py:172 in find_packages
       170│         packages = []
       171│         for repo in self._repositories:
     → 172│             packages += repo.find_packages(dependency)
       173│ 
       174│         return packages

  11  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py:53 in find_packages
        51│ 
        52│         try:
     →  53│             info = self.get_package_info(dependency.name)
        54│         except PackageNotFound:
        55│             self._log(

  10  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py:141 in get_package_info
       139│             return self._get_package_info(name)
       140│ 
     → 141│         return self._cache.store("packages").remember_forever(
       142│             name, lambda: self._get_package_info(name)
       143│         )

   9  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cachy/repository.py:174 in remember_forever
       172│             return val
       173│ 
     → 174│         val = value(callback)
       175│ 
       176│         self.forever(key, val)

   8  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/cachy/helpers.py:6 in value
         4│ def value(val):
         5│     if callable(val):
     →   6│         return val()
         7│ 
         8│     return val

   7  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py:142 in <lambda>
       140│ 
       141│         return self._cache.store("packages").remember_forever(
     → 142│             name, lambda: self._get_package_info(name)
       143│         )
       144│ 

   6  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py:146 in _get_package_info
       144│ 
       145│     def _get_package_info(self, name: str) -> dict:
     → 146│         data = self._get(f"pypi/{name}/json")
       147│         if data is None:
       148│             raise PackageNotFound(f"Package [{name}] not found.")

   5  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/repositories/pypi_repository.py:236 in _get
       234│             # We try to remove the cache and try again
       235│             self._cache_control_cache.delete(self._base_url + endpoint)
     → 236│             json_response = self.session.get(self._base_url + endpoint)
       237│ 
       238│         if json_response.status_code == 404:

   4  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:542 in get
       540│ 
       541│         kwargs.setdefault('allow_redirects', True)
     → 542│         return self.request('GET', url, **kwargs)
       543│ 
       544│     def options(self, url, **kwargs):

   3  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:529 in request
       527│         }
       528│         send_kwargs.update(settings)
     → 529│         resp = self.send(prep, **send_kwargs)
       530│ 
       531│         return resp

   2  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:667 in send
       665│             # Redirect resolving generator.
       666│             gen = self.resolve_redirects(r, request, **kwargs)
     → 667│             history = [resp for resp in gen]
       668│         else:
       669│             history = []

   1  ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:667 in <listcomp>
       665│             # Redirect resolving generator.
       666│             gen = self.resolve_redirects(r, request, **kwargs)
     → 667│             history = [resp for resp in gen]
       668│         else:
       669│             history = []

  TooManyRedirects

  Exceeded 30 redirects.

  at ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/requests/sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│ 
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
      167│ 
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│ 
``` 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey
- **Poetry version**: 1.2.0b2.dev0

**Comment by GallagherCommaJack** [comment]
same issue here, with equally uninformative error messages, even when the package I'm trying to add is on normal pypi

**Comment by mykolasolodukha** [comment]
The issue actually takes place in PyPi.

Check whether the URL `https://pypi.org/pypi/{your-repo-name}/json/` returns 404 or fails with e.g. `TOO_MANY_REDIRECTS`.

Usually the answer is "no", so simply do `poetry cache clear --all pypi`.

If the answer is "yes", go to `.../poetry/repositories/pypi_repository.py` and add the second `try/except` check:
```python
    def _get(self, endpoint):  # type: (str) -> Union[dict, None]
        try:
            json_response = self.session.get(self._base_url + endpoint)
        except requests.exceptions.TooManyRedirects:
            # Cache control redirect loop.
            # We try to remove the cache and try again
            self._cache_control_cache.delete(self._base_url + endpoint)
            try:
                json_response = self.session.get(self._base_url + endpoint)
            except requests.exceptions.TooManyRedirects:
                return None

            ...
```

**Comment by GallagherCommaJack** [comment]
tried that, it's no longer complaining about too many redirects, instead the `resolving dependencies` step appears to be hanging indefinitely with minimal network activity and CPU usage

**Comment by mykolasolodukha** [comment]
@GallagherCommaJack what URL causes the issue in your case?

**Comment by GallagherCommaJack** [comment]
`poetry add numpy`, with or without any custom repository

`pip install numpy` works just fine though

**Comment by GallagherCommaJack** [comment]
here's the `poetry add -vvv numpy` output up until it hangs
```
Updating dependencies
Resolving dependencies...
   1: fact: t5-to-mae-prior-june3 is 0.1.0
   1: derived: t5-to-mae-prior-june3
   1: fact: t5-to-mae-prior-june3 depends on pycontexts (^0.1.4)
   1: fact: t5-to-mae-prior-june3 depends on typing-extensions (^4.2.0)
   1: fact: t5-to-mae-prior-june3 depends on black (^22.3.0)
   1: fact: t5-to-mae-prior-june3 depends on numpy (^1.22.4)
   1: selecting t5-to-mae-prior-june3 (0.1.0)
   1: derived: numpy (>=1.22.4,<2.0.0)
   1: derived: black (>=22.3.0,<23.0.0)
   1: derived: typing-extensions (>=4.2.0,<5.0.0)
   1: derived: pycontexts (>=0.1.4,<0.2.0)
PyPI: No release information found for numpy-0.9.6, skipping
PyPI: No release information found for numpy-0.9.8, skipping
PyPI: No release information found for numpy-1.0.3, skipping
PyPI: No release information found for numpy-1.0.4, skipping
PyPI: No release information found for numpy-1.0b1, skipping
PyPI: No release information found for numpy-1.0b4, skipping
PyPI: No release information found for numpy-1.0b5, skipping
PyPI: No release information found for numpy-1.0rc1, skipping
PyPI: No release information found for numpy-1.0rc2, skipping
PyPI: No release information found for numpy-1.0rc3, skipping
PyPI: No release information found for numpy-1.1.1, skipping
PyPI: No release information found for numpy-1.2.0, skipping
PyPI: No release information found for numpy-1.2.1, skipping
PyPI: No release information found for numpy-1.4.0, skipping
PyPI: 1 packages found for numpy >=1.22.4,<2.0.0
PyPI: Getting info for numpy (1.22.4) from PyPI
PyPI: No dependencies found, downloading archives
PyPI: Downloading sdist: numpy-1.22.4.zip
```

**Comment by GallagherCommaJack** [comment]
actually nevermind, the issue was due to having added the custom repository as an index url in `pip.conf`, after I reverted that and cleared caches everything is working

**Comment by domdfcoding** [comment]
There was an issue with PyPI causing an endless redirect (https://github.com/pypa/warehouse/issues/11535). Should be fixed now.

**Comment by ViggieSmalls** [comment]
I am still getting this error. I tried the following:
* update poetry `poetry self update` (was already latest version 1.1.13)
* `poetry cache clear --all pypi`
* check the url https://pypi.org/pypi/django-crispy-forms/json (works fine)
* installing with pip works fine

I get following error:
```
Using version ^1.14.0 for django-crispy-forms

Updating dependencies
Resolving dependencies... (0.1s)

  TooManyRedirects

  Exceeded 30 redirects.

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/requests/sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│ 
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
      167│ 
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│ 
```
I get the same error when I try to run `poetry update`.

Any suggestions what to try else?

**Comment by simisimon** [comment]
I also get the same error when running `poetry update`.

```
Updating dependencies
Resolving dependencies... (18.9s)

  TooManyRedirects

  Exceeded 30 redirects.

  at ~/.poetry/lib/poetry/_vendor/py3.9/requests/sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│ 
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
      167│ 
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│
```

I already tried `poetry clear cache --all pypi`, but it did not work.  Any other suggestions?

**Comment by g-as** [comment]
https://status.python.org/incidents/lgpr13fy71bk
