### ISSUE TITLE
`poetry build -C` prefixes directory twice

### ISSUE THREAD

**Issue by nishantjr** [python-poetry/poetry#8699]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.5
- **OS version and name**: ArchLinux
- **pyproject.toml**: https://gist.github.com/nishantjr/64adb1088ddc8f41e9cb391836034f12

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When running `poetry build` using the `-C` option with a relative path, the path is prepended twice resulting in files not found.

```
njr@kraken$ poetry new poetry-test
Created package poetry_test in poetry-test
njr@kraken$ cd  poetry-test/
njr@kraken$ git init . # silence some warnings.
Initialized empty Git repository in /tmp/poetry-test/.git/
njr@kraken$ poetry build
Building poetry-test (0.1.0)
  - Building sdist
  - Built poetry_test-0.1.0.tar.gz
  - Building wheel
  - Built poetry_test-0.1.0-py3-none-any.whl
njr@kraken$ cd  ..
njr@kraken$ pwd
/tmp
njr@kraken$ poetry -C poetry-test/ build
Building poetry-test (0.1.0)
  - Building sdist

[Errno 2] No such file or directory: '/tmp/poetry-test/poetry-test/poetry_test/__init__.py'
```

Output with `-vvv`:

```
njr@kraken$ poetry -vvv -C poetry-test/ build
Using virtualenv: /home/njr/.cache/pypoetry/virtualenvs/poetry-test-VqRfSpzI-py3.11
Building poetry-test (0.1.0)
  - Building sdist
Ignoring:
  - Adding: poetry-test/poetry_test/__init__.py
  - Adding: pyproject.toml
  - Adding: README.md

  Stack trace:

  10  /usr/lib/python3.11/site-packages/cleo/application.py:327 in run
       325│
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

   9  /usr/lib/python3.11/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

   8  /usr/lib/python3.11/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

   7  /usr/lib/python3.11/site-packages/cleo/application.py:473 in _run_command
       471│
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

   6  /usr/lib/python3.11/site-packages/cleo/application.py:457 in _run_command
       455│
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   5  /usr/lib/python3.11/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│
     → 119│         status_code = self.execute(io)
       120│
       121│         if status_code is None:

   4  /usr/lib/python3.11/site-packages/cleo/commands/command.py:62 in execute
        60│
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

   3  /usr/lib/python3.11/site-packages/poetry/console/commands/build.py:34 in handle
        32│
        33│             builder = Builder(self.poetry)
     →  34│             builder.build(fmt, executable=env.python)
        35│
        36│         return 0

   2  /usr/lib/python3.11/site-packages/poetry/core/masonry/builder.py:39 in build
        37│
        38│         for builder in builders:
     →  39│             builder(self._poetry, executable=executable).build(target_dir)
        40│

   1  /usr/lib/python3.11/site-packages/poetry/core/masonry/builders/sdist.py:83 in build
        81│
        82│             for file in sorted(files_to_add, key=lambda x: x.relative_to_source_root()):
     →  83│                 tar_info = tar.gettarinfo(
        84│                     str(file.path),
        85│                     arcname=pjoin(tar_dir, str(file.relative_to_source_root())),

  FileNotFoundError

  [Errno 2] No such file or directory: '/tmp/poetry-test/poetry-test/poetry_test/__init__.py'

  at /usr/lib/python3.11/tarfile.py:2037 in gettarinfo
      2033│
      2034│         # Use os.stat or os.lstat, depending on if symlinks shall be resolved.
      2035│         if fileobj is None:
      2036│             if not self.dereference:
    → 2037│                 statres = os.lstat(name)
      2038│             else:
      2039│                 statres = os.stat(name)
      2040│         else:
      2041│             statres = os.fstat(fileobj.fileno())
```

**Comment by dimbleby** [comment]
previously: #8524, perhaps closed a little quickly

**Comment by liortct** [comment]
Hi
I would like to solve this issue as my first contribute to this project.
Can this issue assign to me?

**Comment by Secrus** [comment]
@liortct feel free to work on this and submit a PR

**Comment by nishantjr** [comment]
Thank you!

**Comment by kiffen-schutz** [comment]
Could we get an update on the progress of this fix?

**Comment by the-working-rene** [comment]
I also encountered this and started looking into it - but in the main branch it already is fixed by https://github.com/python-poetry/poetry/pull/9433

The fix is not yet in a released version, but installing poetry from the main branch fixes this.

**Comment by urajat** [comment]
The issue https://github.com/python-poetry/poetry/issues/9432 has been marked as closed on May 28, 2024 after it was fixed by https://github.com/python-poetry/poetry/pull/9433. However, I still don't see the fix in a released version. v1.8.4 went out today, but it doesn't have this fix while the main branch seems to have a refactored version of the fix. Any timeline on when this fix will actually be released?
