### ISSUE TITLE
Cannot use installed version of poetry.

### ISSUE THREAD

**Issue by bgrove-s7** [python-poetry/poetry#9856]
### Description

I've experienced this same issue locally, in a Dockerfile and in a vm today.

```bash
pipx install poetry
poetry --version # returns 1.8.4
poetry env list
```

```
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 316, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
    exit_code: int = super()._run(io)
                     ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 420, in _run
    exit_code = self._run_command(command, io)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 462, in _run_command
    raise error
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 446, in _run_command
    exit_code = command.run(io)
                ^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py", line 117, in run
    return self.execute(io) or 0
           ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/command.py", line 61, in execute
    return self.handle()
           ^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/env/list.py", line 17, in handle
    manager = EnvManager(self.poetry)
                         ^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/command.py", line 23, in poetry
    return self.get_application().poetry
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 129, in poetry
    self._poetry = Factory().create_poetry(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/factory.py", line 58, in create_poetry
    base_poetry = super().create_poetry(cwd=cwd, with_groups=with_groups)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/factory.py", line 50, in create_poetry
    poetry_file = self.locate(cwd)
                  ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/factory.py", line 507, in locate
    raise RuntimeError(
RuntimeError: Poetry could not find a pyproject.toml file in /home/user/foobar or its parents

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 327, in run
    self.render_error(e, io)
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?
```

I get the same error with the following commands:
- init
- install
- version

### Workarounds

None that I can find.

### Poetry Installation Method

pipx

### Operating System

mac os 15.1, Ubuntu 24.04.1 LTS

### Poetry Version

1.8.4

### Poetry Configuration

```bash session
cache-dir = "/home/user/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/user/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
poetry env list -vvv
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 316, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
    exit_code: int = super()._run(io)
                     ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 420, in _run
    exit_code = self._run_command(command, io)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 462, in _run_command
    raise error
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 446, in _run_command
    exit_code = command.run(io)
                ^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py", line 117, in run
    return self.execute(io) or 0
           ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/command.py", line 61, in execute
    return self.handle()
           ^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/env/list.py", line 17, in handle
    manager = EnvManager(self.poetry)
                         ^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/command.py", line 23, in poetry
    return self.get_application().poetry
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 129, in poetry
    self._poetry = Factory().create_poetry(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/factory.py", line 58, in create_poetry
    base_poetry = super().create_poetry(cwd=cwd, with_groups=with_groups)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/factory.py", line 50, in create_poetry
    poetry_file = self.locate(cwd)
                  ^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/factory.py", line 507, in locate
    raise RuntimeError(
RuntimeError: Poetry could not find a pyproject.toml file in /home/user/foobar or its parents

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 327, in run
    self.render_error(e, io)
  File "/home/user/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?
```

**Comment by abn** [comment]
@bgrove-s7 can you provide a `Dockerfile` we can use to reproduce this?

**Comment by bgrove-s7** [comment]
> @bgrove-s7 can you provide a `Dockerfile` we can use to reproduce this?

Sure thing:

```Dockerfile

FROM python:3.12 as install-dependencies

WORKDIR /tmp

## Ensure pip is installed
#RUN python -m ensurepip --upgrade

# Install pipx using ensurepip
RUN pip install pipx

# Ensure pipx's binaries are in PATH
ENV PATH="$PATH:/root/.local/bin"

# Install Poetry via pipx
RUN pipx install poetry

RUN poetry --version

RUN poetry init .

# Rest of normal dockerfile
```

This definitely isn't normally how I'd use poetry in Docker, but it reliably demonstrates the error:

```
0.364 Traceback (most recent call last):                                                                                                                                                                                           
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 316, in run
0.364     exit_code = self._run(io)
0.364                 ^^^^^^^^^^^^^
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
0.364     exit_code: int = super()._run(io)
0.364                      ^^^^^^^^^^^^^^^^
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 420, in _run
0.364     exit_code = self._run_command(command, io)
0.364                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 462, in _run_command
0.364     raise error
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 446, in _run_command
0.364     exit_code = command.run(io)
0.364                 ^^^^^^^^^^^^^^^
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py", line 102, in run
0.364     io.input.bind(self.definition)
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/io/inputs/input.py", line 100, in bind
0.364     self._parse()
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/io/inputs/argv_input.py", line 159, in _parse
0.364     self._parse_argument(token)
0.364   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/io/inputs/argv_input.py", line 253, in _parse_argument
0.364     raise CleoRuntimeError(message)
0.364 cleo.exceptions.CleoRuntimeError: No arguments expected for "init" command, got "."
0.364 
0.364 During handling of the above exception, another exception occurred:
0.364 

0.364 Traceback (most recent call last):
0.364   File "/root/.local/bin/poetry", line 8, in <module>
0.364     sys.exit(main())
0.365              ^^^^^^
0.365   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
0.365     exit_code: int = Application().run()
0.365                      ^^^^^^^^^^^^^^^^^^^
0.365   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 327, in run
0.365     self.render_error(e, io)
0.365   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
0.365     self.set_solution_provider_repository(self._get_solution_provider_repository())
0.365     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.365 AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?

**Comment by abn** [comment]
@bgrove-s7 the `init` command does not accept an argument. But that error definitely should be improved :smile:

**Comment by abn** [comment]
@Secrus should this be handled in celo or poetry?

**Comment by bgrove-s7** [comment]
@abn Ahh! Yes, that's not really a great dockerfile, is it? Maybe this one is a better illustration:

```Dockerfile
FROM python:3.12 as install-dependencies

WORKDIR /tmp

# Install pipx using ensurepip
RUN pip install pipx

# Ensure pipx's binaries are in PATH
ENV PATH="$PATH:/root/.local/bin"

COPY ./pyproject.toml /tmp/
# Install Poetry via pipx
RUN pipx install poetry

RUN poetry config virtualenvs.create false
RUN poetry --version

RUN poetry install

# Rest of normal dockerfile
```

```pyproject.toml
[tool.poetry]
name = "TEST"
version = "0.1.0"
description = "Test Installation
authors = ["someone <me@someone.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.112.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

Running docker build for this also returns the same error:

```
0.431 Traceback (most recent call last):                                                                                                                                                                                           
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 316, in run                                                                                                             
0.431     exit_code = self._run(io)
0.431                 ^^^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
0.431     exit_code: int = super()._run(io)
0.431                      ^^^^^^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 420, in _run
0.431     exit_code = self._run_command(command, io)
0.431                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 462, in _run_command
0.431     raise error
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 446, in _run_command
0.431     exit_code = command.run(io)
0.431                 ^^^^^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py", line 117, in run
0.431     return self.execute(io) or 0
0.431            ^^^^^^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/command.py", line 61, in execute
0.431     return self.handle()
0.431            ^^^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/config.py", line 101, in handle
0.431     local_config_file = TOMLFile(self.poetry.file.path.parent / "poetry.toml")
0.431                                  ^^^^^^^^^^^
0.431   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/commands/command.py", line 23, in poetry
0.431     return self.get_application().poetry
0.432            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 129, in poetry
0.432     self._poetry = Factory().create_poetry(
0.432                    ^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/factory.py", line 58, in create_poetry
0.432     base_poetry = super().create_poetry(cwd=cwd, with_groups=with_groups)
0.432                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/factory.py", line 51, in create_poetry
0.432     local_config = PyProjectTOML(path=poetry_file).poetry_config
0.432                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/pyproject/toml.py", line 57, in poetry_config
0.432     tool = self.data["tool"]
0.432            ^^^^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/core/pyproject/toml.py", line 32, in data
0.432     self._data = tomllib.load(f)
0.432                  ^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 66, in load
0.432     return loads(s, parse_float=parse_float)
0.432            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 102, in loads
0.432     pos = key_value_rule(src, pos, out, header, parse_float)
0.432           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 326, in key_value_rule
0.432     pos, key, value = parse_key_value_pair(src, pos, parse_float)
0.432                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 369, in parse_key_value_pair
0.432     pos, value = parse_value(src, pos, parse_float)
0.432                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 598, in parse_value
0.432     return parse_one_line_basic_str(src, pos)
0.432            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 409, in parse_one_line_basic_str
0.432     return parse_basic_str(src, pos, multiline=False)
0.432            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.432   File "/usr/local/lib/python3.12/tomllib/_parser.py", line 580, in parse_basic_str
0.432     raise suffixed_err(src, pos, f"Illegal character {char!r}")
0.432 tomllib.TOMLDecodeError: Illegal character '\n' (at line 4, column 33)
0.432 
0.432 During handling of the above exception, another exception occurred:
0.432 
0.432 Traceback (most recent call last):
0.432   File "/root/.local/bin/poetry", line 8, in <module>
0.432     sys.exit(main())
0.432              ^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
0.432     exit_code: int = Application().run()
0.432                      ^^^^^^^^^^^^^^^^^^^
0.432   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 327, in run
0.433     self.render_error(e, io)
0.433   File "/root/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
0.433     self.set_solution_provider_repository(self._get_solution_provider_repository())
0.433     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.433 AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?
------
Dockerfile:15
--------------------
  13 |     RUN pipx install poetry
  14 |     
  15 | >>> RUN poetry config virtualenvs.create false
  16 |     RUN poetry --version
  17 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c poetry config virtualenvs.create false" did not complete successfully: exit code: 1
```

The truly strange thing is that Dockerfiles that worked last week are no longer working for us today.

**Comment by abn** [comment]
Yeah this is a cleo release issue, that release might need to be yanked.

Try this:

```sh
pipx inject --force poetry 'cleo<2.2.0'
```

**Comment by bgrove-s7** [comment]
That did it! Thank you!

**Comment by abn** [comment]
@bgrove-s7 I have yanked cleo's `2.2.1` release, the issue should be resolved for now. Thank you for reporting this.

**Comment by Evan0000000000** [comment]
Apologies for reopening this but I'm unclear how to work around this in my environment.

If I `pip install poetry` (noting that my employer maintains their own pypi mirror) I get poetrty 1.8.4 and cleo 2.2.1; I gather from the discussion this combination is causing the issues. The error I get is very similar to the long string of exceptions ending with `AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?` in the original report.

If I uninstall then reinstall with the cleo version noted above, e.g.,:
```
pip uninstall poetry
pip uninstall poetry-core
pip uninstall poetry-plugin-export

pip install cleo<2.2.0
pip install poetry
```
I get poetry 1.8.4 and cleo 2.1.0. Then when I try to install a package this happens:
```
PS C:\workspace\repos\repo> poetry install zeep

No arguments expected for "install" command, got "zeep"
```

I'm not sure if I'm misunderstanding the issue or if the above instruction for use with pipx doesn't translate to pip for reasons I don't intuit.

**Comment by HDembinski** [comment]
Hi, I am still getting the same error. With poetry 1.8.5. Perhaps another version of cleo was released which is still broken?

**Comment by HDembinski** [comment]
I installed poetry with pixi, it is probably related to that.
